# Generated by Django 6.0 on 2026-03-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_region_e04c0b_idx',
            old_name='events_event_region_fa39dd_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_region_23c436_idx',
            old_name='events_event_region_28160f_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_venue_i_b423ce_idx',
            old_name='events_event_venue_i_b6d969_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_slug_30eb0f_idx',
            old_name='events_event_slug_9279cc_idx',
        ),
        migrations.RenameIndex(
            model_name='venue',
            new_name='events_venu_slug_d5deb2_idx',
            old_name='events_venue_slug_41fc6e_idx',
        ),
        migrations.RenameIndex(
            model_name='venue',
            new_name='events_venu_town_a69057_idx',
            old_name='events_venue_town_92baec_idx',
        ),
    ]
