# Generated by Django 6.0 on 2026-01-14 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('oxford', 'Oxford'), ('westoxon', 'West Oxfordshire'), ('eastoxon', 'East Oxfordshire'), ('northoxon', 'North Oxfordshire'), ('southoxon', 'South Oxfordshire')], max_length=20)),
                ('event_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('uncancel', 'Un-cancel'), ('feature', 'Feature'), ('unfeature', 'Un-feature'), ('hide', 'Hide (make not public)'), ('unhide', 'Un-hide (make public)')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acted_at'],
                'indexes': [models.Index(fields=['region', 'event_id'], name='moderation__region_c0f694_idx'), models.Index(fields=['action', 'acted_at'], name='moderation__action_2e48e5_idx')],
            },
        ),
    ]
